module.exports = {
  content: ["./app/**/*.{js,ts,jsx,tsx}", "./components/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        grape: "#8E97FD",
        darkGrape: "#6E78E8",
        darkerGrape: "#5A67D8",
        lightBlue: "#9CD8EC",
        blue: "#6FC3DF",
        darkBlue: "#3FA9C9",
        darkerBlue: "#2B7A8B",
        lightRaspberry: "#FCD1E8",
        raspberry: "#F895C2",
        darkRaspberry: "#E66AAE",
        darkerRaspberry: "#D4559E",
        lightMint: "#B1E3CD",
        mint: "#7FD9B8",
        darkMint: "#2BAB7C",
        darkerMint: "#1E7A5B",
        peach: "#FFCC90",
        lightYellow: "#FCE2B4",
        yellow: "#F6C86B",
        darkYellow: "#E9AA0A",
        darkerYellow: "#C98908",
        charcoal: "#2E3130",
        orange: "#FF9E23",
        background: "#F6F3E6",
        mediumGrey: "#D4D1C3",
      },
      fontFamily: {
        archivo: ["ArchivoBlack", "sans-serif"],
        mono: ["JetBrainsMono", "sans-serif"],
        karla: ["Karla", "sans-serif"],
        gabarito: ["Gabarito", "sans-serif"],
      },
    },
  },
  plugins: [],
};
